name: Secret Debug

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Test secret
        run: |
          if [ -z "${{ secrets.GH_REPO }}" ]; then
            echo "GH_REPO secret is NOT available!"
            exit 1
          else
            echo "GH_REPO secret is available: OK"
          fi